version: '3'
services:
#  redis:
#    image: "redis:latest"
#    ports:
#      - "6379:6379"
#    volumes:
#      - "./data/redis:/data"
  db:
    image: postgres:latest
    container_name: rental-house-db
    ports:
      - "55432:5432"
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DATABASE: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./database/data:/var/lib/postgresql/data
