// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: address.sql

package domains

import (
	"context"
)

const createAddress = `-- name: CreateAddress :one
INSERT INTO address (name, city)
SELECT $1, $2
WHERE NOT EXISTS (
    SELECT name, city
    FROM address
    WHERE name = $1 AND city = $2
)
    RETURNING name, city
`

type CreateAddressParams struct {
	Name string
	City string
}

type CreateAddressRow struct {
	Name string
	City string
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (CreateAddressRow, error) {
	row := q.db.QueryRowContext(ctx, createAddress, arg.Name, arg.City)
	var i CreateAddressRow
	err := row.Scan(&i.Name, &i.City)
	return i, err
}
