// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: city.sql

package domains

import (
	"context"
)

const createCity = `-- name: CreateCity :one
INSERT INTO city (name, prefecture)
SELECT $1, $2
WHERE NOT EXISTS (
    SELECT name, prefecture
    FROM city
    WHERE name = $1 AND prefecture = $2
)
    RETURNING name, prefecture
`

type CreateCityParams struct {
	Name       string
	Prefecture string
}

func (q *Queries) CreateCity(ctx context.Context, arg CreateCityParams) (City, error) {
	row := q.db.QueryRowContext(ctx, createCity, arg.Name, arg.Prefecture)
	var i City
	err := row.Scan(&i.Name, &i.Prefecture)
	return i, err
}
