// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: close_room_event.sql

package domains

import (
	"context"
	"time"
)

const createCloseRoomEvent = `-- name: CreateCloseRoomEvent :one
INSERT INTO close_room_event (room_id, recorded_at)
SELECT $1, $2
WHERE NOT EXISTS (
    SELECT room_id
    FROM close_room_event
    WHERE room_id = $1 AND recorded_at = $2
)
    RETURNING room_id, recorded_at
`

type CreateCloseRoomEventParams struct {
	RoomID     int32
	RecordedAt time.Time
}

type CreateCloseRoomEventRow struct {
	RoomID     int32
	RecordedAt time.Time
}

func (q *Queries) CreateCloseRoomEvent(ctx context.Context, arg CreateCloseRoomEventParams) (CreateCloseRoomEventRow, error) {
	row := q.db.QueryRowContext(ctx, createCloseRoomEvent, arg.RoomID, arg.RecordedAt)
	var i CreateCloseRoomEventRow
	err := row.Scan(&i.RoomID, &i.RecordedAt)
	return i, err
}
