// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: equipment.sql

package domains

import (
	"context"
)

const createEquipment = `-- name: CreateEquipment :one
INSERT INTO equipment (name)
SELECT $1
WHERE NOT EXISTS (
    SELECT name
    FROM equipment
    WHERE name = $1
)
    RETURNING name
`

func (q *Queries) CreateEquipment(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, createEquipment, name)
	err := row.Scan(&name)
	return name, err
}
