// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: floot_plan_type.sql

package domains

import (
	"context"
)

const createFloorPlanType = `-- name: CreateFloorPlanType :one
INSERT INTO floor_plan_type (name)
SELECT $1
WHERE NOT EXISTS (
    SELECT name
    FROM floor_plan_type
    WHERE name = $1
)
    RETURNING name
`

func (q *Queries) CreateFloorPlanType(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, createFloorPlanType, name)
	err := row.Scan(&name)
	return name, err
}
