// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: house.sql

package domains

import (
	"context"
)

const createHouse = `-- name: CreateHouse :one
INSERT INTO house (name, construction_year, structure, address_id, owner_id)
VALUES ($1, $2, $3, $4, $5)
    RETURNING id, name, construction_year, structure, address_id, owner_id
`

type CreateHouseParams struct {
	Name             string
	ConstructionYear int32
	Structure        string
	AddressID        int32
	OwnerID          int32
}

type CreateHouseRow struct {
	ID               int32
	Name             string
	ConstructionYear int32
	Structure        string
	AddressID        int32
	OwnerID          int32
}

func (q *Queries) CreateHouse(ctx context.Context, arg CreateHouseParams) (CreateHouseRow, error) {
	row := q.db.QueryRowContext(ctx, createHouse,
		arg.Name,
		arg.ConstructionYear,
		arg.Structure,
		arg.AddressID,
		arg.OwnerID,
	)
	var i CreateHouseRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ConstructionYear,
		&i.Structure,
		&i.AddressID,
		&i.OwnerID,
	)
	return i, err
}
