// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package domains

import (
	"time"
)

type Access struct {
	Station        string
	MovementMethod string
	TimeInMinutes  int32
	HouseID        int32
}

type Address struct {
	ID   int32
	Name string
	City string
}

type BasementStory struct {
	HouseID int32
	Num     int32
}

type ChangeRentRoomPriceEvent struct {
	ID               int32
	MonthlyRent      int32
	SecurityDeposit  int32
	KeyMoney         int32
	BrokerageFee     int32
	RenewalFee       int32
	GuaranteeFee     int32
	CommonServiceFee int32
	RoomID           int32
	RecordedAt       time.Time
}

type City struct {
	Name       string
	Prefecture string
}

type CloseRoomEvent struct {
	ID         int32
	RoomID     int32
	RecordedAt time.Time
}

type Equipment struct {
	Name string
}

type FloorPlan struct {
	Name          string
	FloorPlanType string
}

type FloorPlanType struct {
	Name string
}

type House struct {
	ID               int32
	Name             string
	ConstructionYear int32
	AddressID        int32
	OwnerID          int32
	Structure        string
}

type MovementMethod struct {
	Name string
}

type OpenRoomEvent struct {
	ID         int32
	RoomID     int32
	RecordedAt time.Time
}

type Owner struct {
	ID        int32
	Name      string
	Tel       string
	AddressID int32
}

type Page struct {
	ID        int32
	Search    string
	WebSiteID int32
}

type Prefecture struct {
	Name string
}

type ReinsTransactionPrice struct {
	ID         int32
	RoomID     int32
	Price      int32
	StartMonth time.Time
	EndMonth   time.Time
}

type Room struct {
	ID      int32
	Name    string
	HouseID int32
}

type RoomEquipment struct {
	RoomID    int32
	Equipment string
}

type RoomMetadatum struct {
	RoomID          int32
	Direction       string
	AreaSquareMeter string
	Floor           int32
	FloorPlan       string
}

type Station struct {
	Name string
}

type StationTrain struct {
	Station string
	Train   string
}

type Story struct {
	HouseID int32
	Num     int32
}

type Structure struct {
	Name string
}

type Train struct {
	Name string
}

type WebSite struct {
	ID   int32
	Host string
}
