// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: movement_method.sql

package domains

import (
	"context"
)

const createMovementMethod = `-- name: CreateMovementMethod :one
INSERT INTO movement_method (name)
VALUES ($1)
    RETURNING name
`

func (q *Queries) CreateMovementMethod(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, createMovementMethod, name)
	err := row.Scan(&name)
	return name, err
}
