// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: room_metadata.sql

package domains

import (
	"context"
)

const createRoomMetadata = `-- name: CreateRoomMetadata :one
INSERT INTO room_metadata (room_id, direction, area_square_meter, floor, floor_plan)
SELECT $1, $2, $3, $4, $5
WHERE NOT EXISTS (
    SELECT room_id
    FROM room_metadata
    WHERE room_id = $1
)
    RETURNING room_id, direction, area_square_meter, floor, floor_plan
`

type CreateRoomMetadataParams struct {
	RoomID          int32
	Direction       string
	AreaSquareMeter string
	Floor           int32
	FloorPlan       string
}

func (q *Queries) CreateRoomMetadata(ctx context.Context, arg CreateRoomMetadataParams) (RoomMetadatum, error) {
	row := q.db.QueryRowContext(ctx, createRoomMetadata,
		arg.RoomID,
		arg.Direction,
		arg.AreaSquareMeter,
		arg.Floor,
		arg.FloorPlan,
	)
	var i RoomMetadatum
	err := row.Scan(
		&i.RoomID,
		&i.Direction,
		&i.AreaSquareMeter,
		&i.Floor,
		&i.FloorPlan,
	)
	return i, err
}
