// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: room.sql

package domains

import (
	"context"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO room (name, house_id)
SELECT $1, $2
WHERE NOT EXISTS (
    SELECT name
    FROM room
    WHERE name = $1 AND house_id = $2
)
    RETURNING id, name, house_id
`

type CreateRoomParams struct {
	Name    string
	HouseID int32
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, createRoom, arg.Name, arg.HouseID)
	var i Room
	err := row.Scan(&i.ID, &i.Name, &i.HouseID)
	return i, err
}
