// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: station_train.sql

package domains

import (
	"context"
)

const createStationTrain = `-- name: CreateStationTrain :one
INSERT INTO station_train (station, train)
SELECT $1, $2
WHERE NOT EXISTS (
    SELECT 1
    FROM station_train
    WHERE station = $1 AND train = $2
)
RETURNING station, train
`

type CreateStationTrainParams struct {
	Station string
	Train   string
}

func (q *Queries) CreateStationTrain(ctx context.Context, arg CreateStationTrainParams) (StationTrain, error) {
	row := q.db.QueryRowContext(ctx, createStationTrain, arg.Station, arg.Train)
	var i StationTrain
	err := row.Scan(&i.Station, &i.Train)
	return i, err
}
