// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: station.sql

package domains

import (
	"context"
)

const createStation = `-- name: CreateStation :one
INSERT INTO station (name)
VALUES ($1)
    RETURNING name
`

func (q *Queries) CreateStation(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, createStation, name)
	err := row.Scan(&name)
	return name, err
}
