// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: structure.sql

package domains

import (
	"context"
)

const createStructure = `-- name: CreateStructure :one
INSERT INTO structure (name)
VALUES ($1)
    RETURNING name
`

func (q *Queries) CreateStructure(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, createStructure, name)
	err := row.Scan(&name)
	return name, err
}
