// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: train.sql

package domains

import (
	"context"
)

const createTrain = `-- name: CreateTrain :one
INSERT INTO train (name)
VALUES ($1)
    RETURNING name
`

func (q *Queries) CreateTrain(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, createTrain, name)
	err := row.Scan(&name)
	return name, err
}
