version: '3'
services:
  db:
    image: postgres:14.1
    container_name: scraper-postgres
    volumes:
      - ./database/data:/var/lib/postgresql/data
    ports:
      - "55433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
  scraper:
    depends_on:
      - db
    container_name: scraper-api
    build: .
    environment:
      - LOG_LEVEL=info
      - ENV=local
      - GOPATH=/go
    volumes:
      - ./:/main
    working_dir: /main
    tty: true
