name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          cache-dependency-path: ./go.sum
      - name: Run go mod download
        run: go mod download
      - name: Run go vet
        run: go vet ./...
      - name: Run go fmt
        run: go fmt ./...
      - name: Run go test
        run: go test -v ./...
      - name: Build go
        run: go build -o ./bin/scraper ./cmd/server/main.go
